language: node_js
node_js: stable
sudo: required
addons:
  chrome: stable
install:
  - npm ci
  - npm i -D @api-components/api-model-generator
script:
  - npm test
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
