language: node_js
node_js: stable
sudo: required
addons:
  chrome: stable
install:
- npm ci
- npm i -D @api-components/api-model-generator
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: bs/R8fIqGoVXubvTt1yju7yoQbNQp0awu2C0XGc9MVdZhWynpkdz2TiZj69/A9xSi3SiOtUpxW163EouUgGrxoik24lycZLCWy6zzIhASTj020bp5PeQTuqIaDRPobVALR9J0lL6ywvrtSKXnISX4LCtV2L1S/M7LzV63jrcj7SbH4m34phERXLNXimlfXsFKCjjnlw+pQkBnoTGWRxQCDUHQBn9plLiXM1BQxL8a4ZOOuZWwr1YbXtE1iWwuXv7bzp9uN9FqYwVtMBMaY0EKdi6eInWPbE80ichzgkblPBNU5KdBwBMhHp8/E+z1GvQua4a6GbIafUCHpNii5WZysUFt4SzmH9zWF5Jd+lDHIf6/skgKjCfmvug3hWtsiBmPf3503hE0HH0zCklNLfnAMpk6+gVeceT4Ea3TDpHchy1wpncp178jFgEGoLCtdWwwStTRqDuzEjU0HOrz0QKBAK8lixTt+QsLi7dW70JGRY6wt356dV6S4XaYyPqTMphXgmrHeyfZj3cVgdQbnoGiRRbciqE3sgMWrBO9HPjsWS8P7B0qwvFYv6tQLXvVwymVKdpxindLC9QANKNe2c0zww+QfAUeo9kFsoXEaxZochRjtiN/9vQYiL+Evu5Y5SQhfStZCfTzOgTSaHyK1e+qCcjEgXA+05Cv7RFwayNrRI=
  - secure: G4jymx5hCwM994G0JMTYC5YD8+Mu34kUeiP83Y54YBFoF8BjZM19MYHK6w44TS8WVIimm2svRX31O0ZjTqtkA3OFa+iym1FKAbK+dqS0O1mieJfRcXsSnIxHoFAH9CZ1ZJlkWTYcxSAUs6LU5MF5gdu/+XwIkdOz6dz9yoXfXfKzIdZTRQ8mF2avdLTGHabAq6ldiRQn2vgxh++7W+gtr9G+kUnlLfA6kijqtiLqx5nLADpo11v8wSJ0SVzyfHFriQY5HHMQw6D8wUkz3pr+d/LFfStAhAWK+ebZlXPMiJODcZxO0TICx8TsfzgpiKsie2xE55XhFXFIx6+nDa4xRQt4O7WMmskXE/hVyxrrYUBc9a0xEk9nlmXhbY4yA1E06uMFsKQxlHmKBwq1nlPoz0iHHHUaQ27mGoozNFs9v3Pb/l4FOuaMAFwyFlsJkIhthGu4HAySWer1jMjs50Kwq5sumCHla3aV55tjQh82K9mDzzrJe4HduyDi9MvWu8H7sCrRCDmX5fOsgUR7ur5yF6daxkqb4v0mOPMoKIpVFwgF0RXLggjRBuWncdyqSv6TLQh0OOAegnr0eGpJGYlQSNJveNM9RSE8lRsxc4Rc8l3Gq+F3yM9FzCpKAtfU2dcrn+ZrODMO1znzQtGP3R9tlF3NCjL6ZNvktsuf3tpTo1c=
