openapi: '3.0.2'
info:
  title: Servers demo API
  version: '1.0'

paths:
  /default:
    description: A default path to the API
    get:
      summary: "A get method"
      responses:
        '200':
          description: Successful response
  /files:
    description: File upload and download operations
    get:
      summary: "A get method"
      responses:
        '200':
          description: Successful response
  /ping:
    get:
      summary: "A get method"
      responses:
        '200':
          description: Successful response
    post:
      summary: "A post method"
      responses:
        '201':
          description: Successful create
